name: "Setup"
description: "Set up the environment"

inputs:
  token:
    description: "A GitHub token."
    required: true
    type: string
  packageManager:
    description: "Package manager to use"
    type: string
    required: false
    default: "yarn"


runs:
  using: "composite"
  steps:
    - name: Install svn
      shell: bash
      run: |
        sudo apt install subversion

    - name: Install NodeJS
      uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
      with:
        node-version-file: ".nvmrc"
        cache: ${{ inputs.packageManager }}

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@4bd44f22a98a19e0950cbad5f31095157cc9621b # v2.25.4 
      with:
        php-version: "7.4"
      env:
        COMPOSER_TOKEN: ${{ inputs.token }}

    - name: Install all dependencies (yarn)
      shell: bash
      if: ${{ 'yarn' == inputs.packageManager }}
      run: |
        composer install || composer update wporg/*
        yarn
        yarn setup:tools

    - name: Build all included projects (yarn)
      shell: bash
      if: ${{ 'yarn' == inputs.packageManager }}
      run: yarn workspaces run build

    - name: Install all dependencies (npm)
      shell: bash
      if: ${{ 'npm' == inputs.packageManager }}
      run: |
        composer install || composer update wporg/*
        npm install
        npm run setup:tools

    - name: Build all included projects (npm)
      shell: bash
      if: ${{ 'npm' == inputs.packageManager }}
      run: npm run build --workspaces --if-present